#!/bin/bash

###============================================================================
###
###         FILE:  demo
###
###        USAGE:  demo
###
###  DESCRIPTION:  Test various features of shellmenu for debugging
###
###      OPTIONS:  --help, --verbose, --quiet
### REQUIREMENTS:  ui-functions, shmenu.conf
###         BUGS:  ---
###        NOTES:  ---
###       AUTHOR:  Michael A. Taylor (mataylortech@gmail.com)
###      COMPANY:  ---
###      VERSION:  Beta
###      CREATED:  04/03/2013
###     REVISION:  04/03/2013
###============================================================================

# Source
. ./ui-functions
. ./shmenu.conf

scriptname=$(basename $0)
TMP=`mktemp /tmp/${scriptname}.XXXXXX`

# Set a trap to remove the temp file when the program exits.
trap cleanup HUP QUIT TERM EXIT
trap interrupt INT

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# FUNCTIONS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

interrupt() {
  ## Trap Cntrl-C, set INT to 1
  INT=1
} # End of interrupt

cleanup() {
  ## Remove temp file if it exists.
  [ -f "$TMP" ] && rm -f $TMP
} # End of cleanup

usage_help() {
  ## Display title header to standard output
  cat "$0" | egrep '^###'
  return 0
} # End of Usage

#------------------------------------------------------------------------------
# PRE-PROCESSING
#------------------------------------------------------------------------------

# Initialize variables and arrays
INT=0

# Parse command-line parameters

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      usage_help
      exit 0
      ;; 
    -v|--verbose)
      verbose=0
      shift
      ;;
    -q|--quiet)
      verbose=1
      shift
      ;;
    -g|--gui)
      GUI=1
      shift
      ;;
    -t|--tui)
      GUI=0
      shift
      ;;
    -c|--cli|--cui)
      GUI=-1
      shift
      ;;
    *)
      ErrorMsg "Invalid parameter" $0
      exit 1
      ;;
  esac
done

#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# MAIN
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

# Set GUI style
sed "s/GUI_DEFAULT=.*/GUI_DEFAULT=$GUI/" "./shmenu.conf" >$TMP
# Backup old config file
cp -f "./shmenu.conf" "./shmenu.conf~"
cp -f $TMP "./shmenu.conf"
. ./shmenu.conf

# Menu Demo
while [ ! $INT = 1 ]; do

  menu_list=(\
    "demo-menu|Show list of menu items"
    "demo-radiolist|Show radiolist-type menu"
    "demo-checklist|Show checklist-type menu"
    "demo-info|Show dialog with a message"
    "demo-error|Show error dialog"
    "demo-warning|Show warning dialog"
    "demo-question|Show OK/Cancel dialog"
    "demo-text|Show contents of a file"
    "demo-entry|Get user input"
    "demo-password|Get user input & hide typed characters (for passwords)"
    "demo-terminal-ui|Demonstrate terminal-only UI functions")
    
    Dlg MENU "shmenu demo" "Demo: Main Menu"
    [ ! $? = 0 ] && set INT=1
    if [ ! -z "$choice" ]; then
      ./$choice
    else
      echo "No Selection"
      INT=1
    fi
  
done
