#!/bin/bash

###============================================================================
###
###         FILE:  demo-setcolor
###
###        USAGE:  demo-setcolor
###
###  DESCRIPTION:  Test various features of shellmenu for debugging
###
###      OPTIONS:  --help, --verbose, --quiet
### REQUIREMENTS:  ui-functions, shmenu.conf
###         BUGS:  ---
###        NOTES:  ---
###       AUTHOR:  Michael A. Taylor (mataylortech@gmail.com)
###      COMPANY:  ---
###      VERSION:  Beta
###      CREATED:  04/03/2013
###     REVISION:  04/03/2013
###============================================================================

# Source
. ./ui-functions
. ./shmenu.conf

scriptname=$(basename $0)
TMP=`mktemp /tmp/${scriptname}.XXXXXX`

# Set a trap to remove the temp file when the program exits.
trap cleanup HUP QUIT TERM EXIT
trap interrupt INT

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# FUNCTIONS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

interrupt() {
  ## Trap Cntrl-C, set INT to 1
  INT=1
} # End of interrupt

cleanup() {
  ## Remove temp file if it exists.
  [ -f "$TMP" ] && rm -f $TMP
} # End of cleanup

usage_help() {
  ## Display title header to standard output
  cat "$0" | egrep '^###'
  return 0
} # End of Usage

#------------------------------------------------------------------------------
# PRE-PROCESSING
#------------------------------------------------------------------------------

# Initialize variables and arrays
INT=0

# Parse command-line parameters

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      usage_help
      exit 0
      ;; 
    -v|--verbose)
      verbose=0
      shift
      ;;
    -q|--quiet)
      verbose=1
      shift
      ;;
    *)
      break
      ;;
  esac
done


#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# MAIN
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

# setcolor demo

while [ ! $INT = 1 ]; do

  menu_list=(\
    "red|setcolor red"
    "blue|setcolor blue"
    "yellow|setcolor yellow"
    "green|setcolor green"
    "purple|setcolor purple"
    "bold|setcolor bold")
    
    Dlg MENU "Test" "Demo: 'setcolor' function"
    [ ! $? = 0 ] && set INT=1
    if [ ! -z "$choice" ]; then
      setcolor $choice
      echo "If you have a color terminal, this text will be in $choice."
      setcolor $normal
      tPause
    else
      echo "No Selection"
      INT=1
    fi
  
done
