#!/bin/bash

###============================================================================
###
###         FILE:  test-error
###
###        USAGE:  test-error
###
###  DESCRIPTION:  Test various features of shellmenu for debugging
###
###      OPTIONS:  --help, --verbose, --quiet
### REQUIREMENTS:  ui-functions, shellmenu.conf
###         BUGS:  ---
###        NOTES:  ---
###       AUTHOR:  Michael A. Taylor (mataylortech@gmail.com)
###      COMPANY:  ---
###      VERSION:  Beta
###      CREATED:  04/16/2013
###     REVISION:  04/16/2013
###============================================================================

# Source
. ./ui-functions
. ./shellmenu.conf

scriptname=$(basename $0)
TMP=`mktemp /tmp/${scriptname}.XXXXXX`

# Set a trap to remove the temp file when the program exits.
trap cleanup HUP QUIT TERM EXIT
trap interrupt INT

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# FUNCTIONS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

interrupt() {
  ## Trap Cntrl-C, set INT to 1
  INT=1
} # End of interrupt

cleanup() {
  ## Remove temp file if it exists.
  [ -f "$TMP" ] && rm -f $TMP
} # End of cleanup

usage_help() {
  ## Display title header to standard output
  cat "$0" | egrep '^###'
  return 0
} # End of Usage

#------------------------------------------------------------------------------
# PRE-PROCESSING
#------------------------------------------------------------------------------

# Initialize variables and arrays
INT=0

# Parse command-line parameters

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      usage_help
      exit 0
      ;; 
    -v|--verbose)
      verbose=0
      shift
      ;;
    -q|--quiet)
      verbose=1
      shift
      ;;
    *)
      break
      ;;
  esac
done


#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# MAIN
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

while [ ! $INT = 1 ]; do

  menu_list=(\
    "submenu_no_option|Dlg ERROR [Quoted text]")
    
  Dlg MENU "$scriptname" "Test Error Dialog"  
    
  case $choice in
    submenu_no_option)
      : # Do nothing
      ;;
    *)
      echo "No Selection"
      exit 0
      ;;
  esac

  ### Usage: Dlg ERROR "Some text goes here."
  ###
  ### This is basically a standard "message box". Always returns exit code 0
  ### unless the message box widget failed to run for some reason.
  ###
  ### NOTE: There is a bug in zenity that ignores the height parameter and makes
  ### the dialog proportionally taller as the text gets longer until it's off the 
  ### screen.

  Dlg ERROR "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce venenatis odio ut dui aliquam ut condimentum arcu bibendum. Suspendisse iaculis, dolor vitae rutrum elementum, massa sapien egestas quam, at malesuada risus nisi id orci. Nam porttitor faucibus arcu eget pretium. Cras laoreet vestibulum urna, eget hendrerit felis rhoncus non. Praesent laoreet dui enim, vitae cursus ipsum. Quisque ac nisl quam, eu pellentesque lacus. Morbi ac massa dui. Vivamus at quam sed enim ornare gravida. Aenean in neque diam, vel malesuada nunc. Nulla facilisi. Fusce nec sem sit amet ipsum egestas tempor vel vitae sem. Praesent ac facilisis massa. In hac habitasse platea dictumst. Etiam ac orci augue, vel facilisis elit. Morbi a purus vitae nisl egestas dictum."
  echo $?
  tPause

done
