#!/bin/bash

###============================================================================
###
###         FILE:  test
###
###        USAGE:  test
###
###  DESCRIPTION:  Test various features of shellmenu for debugging
###
###      OPTIONS:  --help, --verbose, --quiet
### REQUIREMENTS:  ui-functions, shellmenu.conf
###         BUGS:  ---
###        NOTES:  ---
###       AUTHOR:  Michael A. Taylor (mataylortech@gmail.com)
###      COMPANY:  ---
###      VERSION:  Beta
###      CREATED:  04/03/2013
###     REVISION:  04/03/2013
###============================================================================

# Source
. ./ui-functions
. ./shellmenu.conf

scriptname=$(basename $0)
TMP=`mktemp /tmp/${scriptname}.XXXXXX`

# Set a trap to remove the temp file when the program exits.
trap cleanup HUP QUIT TERM EXIT
trap interrupt INT

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# FUNCTIONS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

interrupt() {
  ## Trap Cntrl-C, set INT to 1
  INT=1
} # End of interrupt

cleanup() {
  ## Remove temp file if it exists.
  [ -f "$TMP" ] && rm -f $TMP
} # End of cleanup

usage_help() {
  ## Display title header to standard output
  cat "$0" | egrep '^###'
  return 0
} # End of Usage

#------------------------------------------------------------------------------
# PRE-PROCESSING
#------------------------------------------------------------------------------

# Initialize variables and arrays
INT=0

# Parse command-line parameters

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      usage_help
      exit 0
      ;; 
    -v|--verbose)
      verbose=0
      shift
      ;;
    -q|--quiet)
      verbose=1
      shift
      ;;
    *)
      break
      ;;
  esac
done


#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# MAIN
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

while [ ! $INT = 1 ]; do

  menu_list=(\
    "submenu_no_option|Dlg INFO [Quoted text]")
    
  Dlg MENU "$scriptname" "Test Information (Message Box) dialog"  
    
  case $choice in
    submenu_no_option)
      : # Do nothing
      ;;
    *)
      echo "No Selection"
      exit 0
      ;;
  esac

  ### Usage: Dlg INFO "Some text goes here."
  ###
  ### This is basically a standard "message box". Always returns exit code 0
  ### unless the message box widget failed to run for some reason.
  ###
  ### NOTE: There is a bug in zenity that ignores the height parameter and makes
  ### the dialog proportionally taller as the text gets longer until it's off the 
  ### screen.

  Dlg INFO "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce venenatis odio ut dui aliquam ut condimentum arcu bibendum. Suspendisse iaculis, dolor vitae rutrum elementum, massa sapien egestas quam, at malesuada risus nisi id orci. Nam porttitor faucibus arcu eget pretium. Cras laoreet vestibulum urna, eget hendrerit felis rhoncus non. Praesent laoreet dui enim, vitae cursus ipsum. Quisque ac nisl quam, eu pellentesque lacus. Morbi ac massa dui. Vivamus at quam sed enim ornare gravida. Aenean in neque diam, vel malesuada nunc. Nulla facilisi. Fusce nec sem sit amet ipsum egestas tempor vel vitae sem. Praesent ac facilisis massa. In hac habitasse platea dictumst. Etiam ac orci augue, vel facilisis elit. Morbi a purus vitae nisl egestas dictum.
  
Fusce iaculis elementum massa ac luctus. Donec purus magna, elementum at lacinia ac, varius vel nisl. Nam sed diam neque, nec gravida est. Integer semper magna ac neque egestas pretium. Pellentesque fermentum dui eu felis dapibus volutpat. Praesent aliquet velit a massa pretium sollicitudin. Fusce felis ligula, pretium in congue sed, dictum ut metus. Quisque tellus diam, luctus non varius sed, tristique nec sem. Donec consectetur luctus lorem, et porttitor nunc ultrices tincidunt. Phasellus elementum est at sapien tristique eleifend. Nunc ut nunc fermentum nibh lacinia sollicitudin. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam rhoncus consequat augue, et rutrum massa adipiscing vel. Curabitur quis neque velit, sit amet rutrum mi. Quisque iaculis porttitor est, quis hendrerit nunc pulvinar nec. Donec quis felis leo, id posuere libero."

  echo $?

done
