#!/bin/bash

###============================================================================
###
###         FILE:  test
###
###        USAGE:  test
###
###  DESCRIPTION:  Test various features of shellmenu for debugging
###
###      OPTIONS:  --help, --verbose, --quiet
### REQUIREMENTS:  ui-functions, shellmenu.conf
###         BUGS:  ---
###        NOTES:  ---
###       AUTHOR:  Michael A. Taylor (mataylortech@gmail.com)
###      COMPANY:  ---
###      VERSION:  Beta
###      CREATED:  04/03/2013
###     REVISION:  04/03/2013
###============================================================================

# Source
. ./ui-functions
. ./shellmenu.conf

scriptname=$(basename $0)
TMP=`mktemp /tmp/${scriptname}.XXXXXX`

# Set a trap to remove the temp file when the program exits.
trap cleanup HUP QUIT TERM EXIT
trap interrupt INT

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# FUNCTIONS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

interrupt() {
  ## Trap Cntrl-C, set INT to 1
  INT=1
} # End of interrupt

cleanup() {
  ## Remove temp file if it exists.
  [ -f "$TMP" ] && rm -f $TMP
} # End of cleanup

usage_help() {
  ## Display title header to standard output
  cat "$0" | egrep '^###'
  return 0
} # End of Usage

#------------------------------------------------------------------------------
# PRE-PROCESSING
#------------------------------------------------------------------------------

# Initialize variables and arrays
INT=0

# Parse command-line parameters

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      usage_help
      exit 0
      ;; 
    -v|--verbose)
      verbose=0
      shift
      ;;
    -q|--quiet)
      verbose=1
      shift
      ;;
    *)
      break
      ;;
  esac
done


#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# MAIN
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

while [ ! $INT = 1 ]; do

  menu_list=(\
    "test-menu|Show list of menu items"
    "test-radiolist|Show radiolist-type menu"
    "test-checklist|Show checklist-type menu"
    "test-info|Show dialog with a message"
    "test-error|Show error dialog"
    "test-warning|Show warning dialog"
    "test-question|Show OK/Cancel dialog"
    "test-text|Show contents of a file"
    "test-entry|Get user input"
    "test-password|Get user input & hide typed characters (for passwords)"
    "test-terminal-ui|Demonstrate terminal-only UI functions")
    
    Dlg MENU "Test" "Test: Main Menu"
    [ ! $? = 0 ] && set INT=1
    if [ ! -z "$choice" ]; then
      ./$choice
    else
      echo "No Selection"
      INT=1
    fi
  
done
