#!/bin/bash

###============================================================================
###
###         FILE:  wrapup
###
###        USAGE:  wrapup
###
###  Description:  Quickly archive everything
###
###      OPTIONS:  --help, --verbose, --quiet, -cui, -tui, -gui
### REQUIREMENTS:  ui-functions, shmenu.conf
###         BUGS:  ---
###        NOTES:  ---
###       AUTHOR:  Michael A. Taylor (mataylortech@gmail.com)
###      COMPANY:  ---
###      VERSION:  Beta
###      CREATED:  04/03/2013
###     REVISION:  04/03/2013
###============================================================================

# Source
. ./ui-functions
. ./shmenu.conf

scriptname=$(basename $0)
TMP=`mktemp /tmp/${scriptname}.XXXXXX`

# Set a trap to remove the temp file when the program exits.
trap cleanup HUP QUIT TERM EXIT
trap interrupt INT

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# FUNCTIONS
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

interrupt() {
  ## Trap Cntrl-C, set INT to 1
  INT=1
} # End of interrupt

cleanup() {
  ## Remove temp file if it exists.
  [ -f "$TMP" ] && rm -f $TMP
} # End of cleanup

usage_help() {
  ## Display title header to standard output
  cat "$0" | egrep '^###'
  return 0
} # End of Usage

#------------------------------------------------------------------------------
# PRE-PROCESSING
#------------------------------------------------------------------------------

# Initialize variables and arrays
INT=0

# Parse command-line parameters

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      usage_help
      exit 0
      ;; 
    -v|--verbose)
      verbose=0
      shift
      ;;
    -q|--quiet)
      verbose=1
      shift
      ;;
    -g|--gui)
      GUI=1
      shift
      ;;
    -t|--tui)
      GUI=0
      shift
      ;;
    -c|--cli|--cui)
      GUI=-1
      shift
      ;;
    *)
      ErrorMsg "Invalid parameter" $0
      exit 1
      ;;
  esac
done

#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# MAIN
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

# Set GUI style
sed "s/GUI_DEFAULT=.*/GUI_DEFAULT=$GUI/" "./shmenu.conf" >$TMP
# Backup old config file
cp -f "./shmenu.conf" "./shmenu.conf~"
cp -f $TMP "./shmenu.conf"
. ./shmenu.conf

# Wrap-up all files into an archive.

folder=$(basename $PWD)
pushd ..
tar -cvzf ~/Dropbox/Private/devscripts/shmenu/shmenu_`date +%y%m%d`.tar.gz $folder --exclude=".git*"
popd
#${f[*]}

